CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name TEXT NOT NULL,
    country TEXT NOT NULL,
    email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category_id BIGINT REFERENCES categories (category_id),
    supplier_id BIGINT REFERENCES suppliers (supplier_id),
    sku TEXT NOT NULL UNIQUE,
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    cost_price NUMERIC(12, 2) NOT NULL CHECK (cost_price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories (category_id),
    ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES suppliers (supplier_id),
    ADD COLUMN IF NOT EXISTS unit_price NUMERIC(12, 2),
    ADD COLUMN IF NOT EXISTS cost_price NUMERIC(12, 2);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'products'
          AND column_name = 'list_price'
    ) THEN
        UPDATE products SET unit_price = list_price WHERE unit_price IS NULL;
        ALTER TABLE products ALTER COLUMN list_price DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'products'
          AND column_name = 'unit_cost'
    ) THEN
        UPDATE products SET cost_price = unit_cost WHERE cost_price IS NULL;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS stores (
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    opened_at DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE stores
    ADD COLUMN IF NOT EXISTS country TEXT,
    ADD COLUMN IF NOT EXISTS opened_at DATE;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'stores'
          AND column_name = 'store_code'
    ) THEN
        ALTER TABLE stores ALTER COLUMN store_code DROP NOT NULL;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory (
    store_id BIGINT NOT NULL REFERENCES stores (store_id),
    product_id BIGINT NOT NULL REFERENCES products (product_id),
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    reorder_level INTEGER NOT NULL CHECK (reorder_level >= 0),
    PRIMARY KEY (store_id, product_id)
);

ALTER TABLE inventory
    ADD COLUMN IF NOT EXISTS quantity INTEGER,
    ADD COLUMN IF NOT EXISTS reorder_level INTEGER;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'inventory'
          AND column_name = 'snapshot_date'
    ) THEN
        ALTER TABLE inventory
            ALTER COLUMN snapshot_date SET DEFAULT CURRENT_DATE;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'inventory'
          AND column_name = 'quantity_on_hand'
    ) THEN
        ALTER TABLE inventory
            ALTER COLUMN quantity_on_hand SET DEFAULT 0;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS sales (
    sale_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers (customer_id),
    store_id BIGINT NOT NULL REFERENCES stores (store_id),
    sale_date TIMESTAMPTZ NOT NULL,
    payment_method TEXT NOT NULL,
    total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sales
    ADD COLUMN IF NOT EXISTS customer_id BIGINT REFERENCES customers (customer_id),
    ADD COLUMN IF NOT EXISTS sale_date TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS payment_method TEXT,
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(14, 2) DEFAULT 0;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'sales'
          AND column_name = 'sold_at'
    ) THEN
        UPDATE sales SET sale_date = sold_at WHERE sale_date IS NULL;
        ALTER TABLE sales ALTER COLUMN sold_at DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'sales'
          AND column_name = 'product_id'
    ) THEN
        ALTER TABLE sales ALTER COLUMN product_id DROP NOT NULL;
        ALTER TABLE sales ALTER COLUMN quantity DROP NOT NULL;
        ALTER TABLE sales ALTER COLUMN unit_price DROP NOT NULL;
    END IF;

    UPDATE sales SET sale_date = CURRENT_TIMESTAMP WHERE sale_date IS NULL;
    ALTER TABLE sales ALTER COLUMN sale_date SET NOT NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS sale_items (
    sale_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sales (sale_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products (product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    discount NUMERIC(5, 2) NOT NULL DEFAULT 0
        CHECK (discount >= 0 AND discount <= 100)
);

CREATE TABLE IF NOT EXISTS returns (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sales (sale_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products (product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    return_date TIMESTAMPTZ NOT NULL,
    reason TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers_orders (
    supplier_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES suppliers (supplier_id),
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS purchase_items (
    purchase_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_order_id BIGINT NOT NULL
        REFERENCES suppliers_orders (supplier_order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products (product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC(12, 2) NOT NULL CHECK (unit_cost >= 0)
);

CREATE INDEX IF NOT EXISTS sales_sale_date_idx ON sales (sale_date);
CREATE INDEX IF NOT EXISTS sales_store_date_idx ON sales (store_id, sale_date);
CREATE INDEX IF NOT EXISTS sale_items_product_idx ON sale_items (product_id);
CREATE INDEX IF NOT EXISTS returns_return_date_idx ON returns (return_date);
